### PR TITLE
Ldns 1.7.0

### PR DESCRIPTION
**Pull request by mattias-p**
This import consists of the following parts:
1. `zonemaster-ldns/src/ldns/*.c` are copied from `ldns/` (not all of `ldns/*.c`)
2. `zonemaster-ldns/src/ldns/compat/*.c` are copied from `ldns/compat/` (not all of `ldns/compat/*.c`)
3. `ldns/ldns/*.h` are copied into `zonemaster-ldns/include/ldns/`
4. `ldns/ldns/*.h.in` are rendered and copied into `zonemaster-ldns/include/ldns/`

### CODE REVIEW

**Comment by mattias-p** [comment]
It seems that `Zonemaster::LDNS->new()` somehow messes with the output streams for some versions of `Test::More`, causing some TAP output to be discarded for some subtests.

I've been able to reproduce this locally with the `Test::More` that comes with Perl 5.20. From the looks of the Travis results `Test::More` has been updated to deal with whatever the cause is in Perl 5.24. The problem also goes away when I use `Test::More` 1.302120 from CPAN.

**Comment by mattias-p** [comment]
So Travis is happy again. But depending on what dependencies get pulled in this might not work during installation. I can see three ways forward:
* Add instructions to install Test::More from CPAN (both for Zonemaster-LDNS and Zonemaster-Engine).
* Update unit test code to work with older Test::More.
* Update Zonemaster::LDNS::new to work with older Test::More.

**Comment by matsduf** [comment]
When I test install Zonemaster-LDNS on Ubuntu 14.04 i see no problem. It has Perl version v5.18.2 and Test::More version 0.98. I ran with `TEST_WITH_NETWORK=1`.

**Comment by mattias-p** [comment]
CentOS doesn't install the Perl core version of Test::More but instead takes it from Test-Simple 0.98. The test suite passes with this setup.

@matsduf Have you checked the origin of your Test::More?

**Comment by matsduf** [comment]
From Ubuntu 14.04:

```
$ perl -e 'use Test::More; print $Test::More::VERSION, "\n";'
0.98

$ find / -name More.pm 2> /dev/null 
/usr/share/perl/5.18.2/Test/More.pm

$ dpkg -S /usr/share/perl/5.18.2/Test/More.pm
perl-modules: /usr/share/perl/5.18.2/Test/More.pm

$ apt-cache show perl-modules
Package: perl-modules
Architecture: all
Version: 5.18.2-2ubuntu1.3
Priority: important
Section: perl
Source: perl
Origin: Ubuntu
(...)
```

**Comment by mattias-p** [comment]
@matsduf So it's Test::More on Ubuntu, but apparently not patched the same way as on Debian.

I tried to test this on Debian 9, but I had a new compilation issue.

```
x86_64-linux-gnu-gcc -c  "-Iinclude" "-I." "-I." -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"1.0.2\" -DXS_VERSION=\"1.0.2\" -o src/ldns/dnssec.o -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"  -DUSE_PPPORT -DWE_CAN_HAZ_IDN src/ldns/dnssec.c
src/ldns/dnssec.c: In function ‘ldns_convert_dsa_rrsig_asn12rdf’:
src/ldns/dnssec.c:1761:12: error: dereferencing pointer to incomplete type ‘DSA_SIG {aka struct DSA_SIG_st}’
  R = dsasig->r;
            ^~
src/ldns/dnssec.c: In function ‘ldns_convert_ecdsa_rrsig_asn1len2rdf’:
src/ldns/dnssec.c:1870:15: error: dereferencing pointer to incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
  r = ecdsa_sig->r;
               ^~
Makefile:728: recipe for target 'src/ldns/dnssec.o' failed
```

**Comment by mattias-p** [comment]
I've tested Debian 7 and Ubuntu 1604 as well and it works there as well.

It seems that Debian 8 is the only OS version affected.

**Comment by wtoorop** [comment]
I just looked at ldns code for the error on Debian 9.  The error would not have happened when HAVE_DSA_SIG_GET0 and HAVE_ECDSA_SIG_GET0 would have been defined.  With a native ldns these would be defined because configure.ac detects the DSA_SIG_get0() and ECDSA_SIG_get0() functions.

Looking at Makefile.PL, I notive you already have some OpenSSL capability testing.  The path forward might be, to:
  - reproduce the other OpenSSL capability testing from configure.ac  in Makefile.PL, or 
  - somehow run configure from Makefile.PL, or
  - prefer an already installed ldns and only fallback to compile if it isn't there.

**Comment by mattias-p** [comment]
@wtoorop Thank you very much for digging into this. Your input has been very helpful in working this out.

Closing this PR in favor #41 which uses a git submodule instead of static copies.

**Pull request closed without merging**
