### PR TITLE
Update licensing

### PR DESCRIPTION
**Pull request by mattias-p**
* Include Afnic as copyright holder
 * Update name of IIS
 * Update language around copyright holders and contributors
 * Update formatting
 * Update years of copyright

### CODE REVIEW

**Comment by matsduf** [comment]
Makefile.PL says 'bsd'. Shouldn't it rather say 'https://opensource.org/licenses/BSD-2-Clause'?

**Comment by mattias-p** [comment]
@matsduf No, this field is a token, not a url.
http://search.cpan.org/~ether/Module-Install-1.18/lib/Module/Install.pod#license

**Comment by matsduf** [comment]
@mattias-p, ok for license string, but the license file must recognize the copyright and license of the NetLabs' LDNS code included.

**Comment by mattias-p** [comment]
@matsduf, doesn't that give them claim over the entirety of the Zonemaster::LDNS? Is that what we want? Their role is already clarified both in README.md and CONTRIBUTORS.txt.

**Comment by matsduf** [comment]
It should say something  like "portions of the code copyright NLnet Labs. For license of that portion see ...".

**Pull request merged**
